#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/ebi_tree
#
# IDENTIFICATION
#    src/backend/storage/ebi_tree/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/ebi_tree
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	ebi_tree.o \
	ebi_tree_buf.o \
	ebi_tree_hash.o \
	ebi_tree_utils.o \
	ebi_sub_buf.o \
	ebi_sub_hash.o \

include $(top_srcdir)/src/backend/common.mk
