#
# Makefile for the LOCATOR module
#
# src/backend/locator/Makefile
#

subdir = src/backend/locator
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS		= executor partitioning catalog storage mempart hap

include $(top_srcdir)/src/backend/common.mk
