#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator/mempart
#
# IDENTIFICATION
#    src/backend/locator/mempart/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/locator/mempart
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	locator_mempart.o

include $(top_srcdir)/src/backend/common.mk
