#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/ebi
#
# IDENTIFICATION
#    src/backend/access/ebi/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/ebi
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	ebiam.o \

include $(top_srcdir)/src/backend/common.mk
