#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator/hap/catalog
#
# IDENTIFICATION
#    src/backend/locator/hap/catalog/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/locator/hap/catalog
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	hap_catalog.o \
	pg_locator_hap.o \
	pg_locator_hap_hidden_attribute_desc.o \
	pg_locator_hap_encoded_attribute.o \
	pg_locator_hap_partition_map.o

include $(top_srcdir)/src/backend/common.mk
