#
# Makefile for the Hidden Attribute Partitioning (HAP) module
#
# src/backend/locator/hap/Makefile
#

subdir = src/backend/locator/hap
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = access catalog state encoding planner reduction partition executor

include $(top_srcdir)/src/backend/common.mk
