#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator/hap/planner
#
# IDENTIFICATION
#    src/backend/locator/hap/planner/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/locator/hap/planner
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	hap_planner.o \
	hap_propagate.o \
	hap_encoding_table.o \
	hap_selectivity.o

include $(top_srcdir)/src/backend/common.mk
