#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator/hap/reduction
#
# IDENTIFICATION
#    src/backend/locator/hap/reduction/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/locator/hap/reduction
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	hap_reduction.o \
	hap_substitution_cache.o \

include $(top_srcdir)/src/backend/common.mk
