#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator/storage
#
# IDENTIFICATION
#    src/backend/locator/storage/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/locator/storage
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	locator_md.o

include $(top_srcdir)/src/backend/common.mk
