#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator/catalog
#
# IDENTIFICATION
#    src/backend/locator/cataloag/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/locator/catalog
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	locator_catalog.o \
	pg_locator.o \

include $(top_srcdir)/src/backend/common.mk
