#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator/executor
#
# IDENTIFICATION
#    src/backend/locator/executor/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/locator/executor
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = locator_executor.o \

include $(top_srcdir)/src/backend/common.mk
